apiVersion: v1
kind: Service
metadata:
  namespace: dcp-rta-app
  name: galera-rs
  labels:
    app: galera-rs
spec:
  type: NodePort
  ports:
    - nodePort: 30306
      port: 3306
  selector:
    app: galera
