kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: dcp-rta-app
  name: galera
  labels:
    app: galera
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: galera
  template:
    metadata:
      labels:
        app: galera
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                    - galera-rs
              topologyKey: kubernetes.io/hostname
      volumes:
      - hostPath:
          path: /opt/data/rta/mysql
        name: mysql-data
      nodeSelector:
        mysql-node: "true"
      imagePullSecrets:
      - name: iotanalyticsregistry.azurecr.io
      containers:
      - name: galera
        image: iotanalyticsregistry.azurecr.io/3pp/mariadb:10.1.43
        volumeMounts:
        - name: mysql-data
          mountPath: "/var/lib/mysql"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: DISCOVERY_SERVICE
          value: "etcd1:2379,etcd2:2379,etcd3:2379"
        - name: XTRABACKUP_PASSWORD
          value: "123456"
        - name: CLUSTER_NAME
          value: "mariadb_galera"
        - name: MYSQL_DATABASE
          value: "testdb"
        - name: MYSQL_USER
          value: "test_user"
        - name: MYSQL_PASSWORD
          value: "test_password"
        readinessProbe:
          exec:
            command:
            - '/healthcheck.sh'
            - '--readiness'
          initialDelaySeconds: 120
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - '/healthcheck.sh'
            - '--liveness'
          initialDelaySeconds: 120
          periodSeconds: 1
